name: TUnit Tests

on:
  workflow_dispatch:
    inputs:
      run_playwright:
        description: 'Run Playwright tests'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/Testing/TUnit/TUnitTesting.Tests

      - name: Build
        run: dotnet build --no-restore -c Release
        working-directory: src/Testing/TUnit/TUnitTesting.Tests

      - name: Run Tests without Playwright
        if: ${{ !inputs.run_playwright }}
        run: dotnet test --no-build -c Release --verbosity normal  --treenode-filter "/*/(!*Playwright*)/*/*"
        working-directory: src/Testing/TUnit/TUnitTesting.Tests

      - name: Install Playwright Browsers
        if: ${{ inputs.run_playwright }}
        working-directory: src/Testing/TUnit
        run: pwsh TUnitTesting.Tests/bin/Release/net10.0/playwright.ps1 install --with-deps chromium

      - name: Run Tests With Playwright
        if: ${{ inputs.run_playwright }}
        run: dotnet test --no-build -c Release --verbosity normal
        working-directory: src/Testing/TUnit/TUnitTesting.Tests